# Generated by Django 4.2 on 2023-04-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artikel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("judul", models.CharField(max_length=50)),
                ("isi", models.TextField()),
                ("kategori", models.CharField(max_length=50)),
                ("slug", models.SlugField(blank=True, editable=False)),
                ("publish", models.DateTimeField(auto_now_add=True)),
                ("update", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
